### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by KeiranGlynn** [ByteClubGames/YumiAndTheYokai#115]

**Comment by KeiranGlynn** [comment]
The first thing that I would like you to do is combine the two health scripts (human and ferrox) together as much as possible. If you think that they will work well together as one single unified script, then go ahead and do that. If you think that they should be separate to increase clarity and readability, then make the ferrox health inherit as much as possible from human health. (If you choose the later of those two options, please rename ferrox health to YokaiHealth). 

Currently there are two methods, IsAlive and SetAlive, being called on Update() in both versions of the health script. Please call SetAlive from the TakeDamage function so that it isn't needlessly being called every frame. Next, rewrite SetAlive so that it calls IsAlive directly. 

Please rewrite the IsAlive function for the Yokai so that it uses the new YokaiSwitcher and InputListner scripts to despawn the yokai when it dies. 

You may have noticed that many of these scripts are using 2D functions, and functions that reference objects by their Rigid Bodies. Please rewrite these functions in their 3D forms, and try to reference game objects as a game object, without calling their RigidBody, if possible.

Lastly, the Respawn function in the Health script, as well as the CheckPoint and RespawnManager scripts may need to be adjusted to work properly. 

If you have any questions, especially about the respawn and checkpoint stuff, please let me know.

**Comment by Persomatey** [comment]
Check it out now (funk soul brotha)
