### ISSUE TITLE
Wind Spell

### ISSUE THREAD

**Issue by Evanito** [ByteClubGames/YumiAndTheYokai#12]
woosh

All design elements are with touch controls in mind.

#### Pre:
1) User short taps a button marked to start the spell.

#### During:
1) (Spell casting idle animation) Player is frozen while spell casting mode is started. A short tap anywhere will cancel the spell.
(?) Maybe have cancel button instead in the place where the cast button was.
2) Dragging started from the character (or very near with no obstacles) will begin the actual spell.
(?) Some sort of visual cue that the spell has started, such as a burst of air particles or different idle animation.
3) User drags the air spell, which will be an invisible trigger under their finger. Every x time spawn an air particle to make a visual trail while it travels.
4) If the (invisible) spell trigger hits:
- The environment: destroy spell.
- An enemy: ??? & destroy spell.
- A wind switch: toggle the switch's activation flag & destroy spell.
5) Return control to player and end spell mode.

**Comment by Jackbruce0** [comment]
UPDATE:
dragging finger spawns "waypoint" objects per distance.
once complete
-windspell object flows from player through checkpoints

**Comment by Evanito** [comment]
Most things are done, needs wall collisions for death

**Comment by KeiranGlynn** [comment]
Content Merged through Issue-#-20-SpellButtons.
