### ISSUE TITLE
Make Spell Buttons

### ISSUE THREAD

**Issue by Persomatey** [ByteClubGames/YumiAndTheYokai#20]
Make buttons that, when pressed, will activate the spells.

**Comment by Jackbruce0** [comment]
I made one button... But you can turn it into all of the other buttons

**Comment by Persomatey** [comment]
Make four button UI's and make them each one function with each of the spells
- Astral Projection Button
- Wind Spell Button 
- Earth Spell Button 
- Ice Spell Button 
Also set the timescale to super slow motion when the casting phase is active for each of the spells, then reset the time scale back to 1 when the casting phase is done and the spell commences.

**Comment by Jackbruce0** [comment]
I made buttons for all spells except Yokai. Issue #20 branch
