### ISSUE TITLE
Bug: Player Jump Ceiling Sticking

### ISSUE THREAD

**Issue by flarros** [ByteClubGames/YumiAndTheYokai#39]
The player sticks to ceiling when holding down jump. (For both the human and yoki)

**Comment by KeiranGlynn** [comment]
I fixed this bug within the "Human Movement Gym," so load that scene up to test it out.

**Comment by KeiranGlynn** [comment]
I'm not merging this to Master because with the changes I made on Issue-#-74, these changes are pretty irrelevant.
