### ISSUE TITLE
Examine and link up Jump Script

### ISSUE THREAD

**Issue by flarros** [ByteClubGames/YumiAndTheYokai#74]
As per what we spoke of, branch off master and examine Hunter's old jump script as well as the modified variant you used in the Checkpoint system branch.

Ideally condense them down to a singular script while maintaining the greatest functionality

(ASWD, Swipe, Ground Checking for both 2D and 3D environmental objects)

**Comment by KeiranGlynn** [comment]
The current script attached to the player on the master branch is what we want to use. Also, I fixed the GroundCheck bug I DM'ed you about. Jump-Friendly surfaces need to be tagged as the current "Platforms" layer on the master branch. If we change the index number of this layer down the line, our Jump script will need to be edited.
