### ISSUE TITLE
WindSpell Touch-Up

### ISSUE THREAD

**Issue by KeiranGlynn** [ByteClubGames/YumiAndTheYokai#89]

**Comment by Evanito** [comment]
1) particles have collisions?
2) physics of colliding with props is weird
3) collides with player during drawing (see 1?)

**Comment by Evanito** [comment]
- only one wind spell can be drawn at once
- time slows to 5% during drawing, slowly accelerates to normal once cast. Ice and Earth slow to 50% instead
- 5 second limit on draw time
- path of wind spell is smoothed out and looks less janky
- still needs visual confirmation that player is casting a spell
- deactivated testenemy, caused many problems and isnt reflective of enemy in game
